### ISSUE TITLE
Better way to implement diamond and square functions?

### ISSUE THREAD

**Issue by AlexRego** [pearselab/r-world-AlexRego#1]
In my current implementation of my diamond and square functions, I find the corners, centers, and north/east/south/west points based on my original matrix. The problem is-- I can't imagine a way that this would be used to continuously find the corners/centers of each successive square created within the matrix. Perhaps if I were to somehow continually segment my matrix into smaller matrices, apply the diamond_square functions to each, then when no NAs are remaining, bind them all back together. Seems messy though. 

I was thinking that I might modify my diamond function so that it calculates the corners of any square of points in the matrix by evaluating the distance of 4 points (that are not NAs) from each other and inputting their average into the center.  Similarly, I would like a square function that finds any center point based on a point's distance to 4 other non-NA points, and subsequently adds an average to the middle of each of those 4 corners. 

If the above were to be implemented, I think that it would be relatively easy to recursively add points until NAs are no longer present in the matrix. However, I am struggling to find a way to identify correct corners and centers, and subsequently placing values where they belong.

Are there any functions or ways of going about this that I might read up on to help? Or perhaps another method would be more functional. Any thoughts/response is appreciated.

**Comment by willpearse** [comment]
The alternative way of thinking that you outline is, for the most part, the one I used to implement this. So I have a lot of sympathy for your way of thinking! That said, let me see if I can convince you to "come back" to doing it using the functions you've already written.

Take a look at my slides again. You'll see that I suggest you implement this in three steps: write a step function, write a diamond function, then write something that wraps around both. You've done the first two: what you must _now_ do is write the wrapper.

This is the "messy" thing you are desperate not to do. It needn't be messy, however, if you _subset_ your matrix. Consider:

``` R
matrix <- matrix(1:25, 5, 5)
matrix[1:3,1:3]
matrix[1:3,1:3] <- matrix[1:3,1:3] * 2
```

...does this seem messy to you? Because it's a way of pulling out subsets of a matrix and manipulating them, and doesn't require you to pull things apart and put them back together. Make sense?
